### ISSUE TITLE
cloudflare

### ISSUE THREAD

**Issue by mortem90** [emreertunc/idata-appointment-checker#1]
cloudflare doğrulamasını nasıl geçeceğim

**Comment by emreertunc** [comment]
geliştirme esnasında cloudflare koruması yoktu. selenium-stealth vb. kullanılarak ek geliştirme yapılabilir.

**Comment by emreertunc** [comment]
geliştirme esnasında cloudflare koruması yoktu. selenium-stealth vb. kullanılarak ek geliştirme yapılabilir.
